name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        django-version: ["4.2", "5.0", "6.0"]
        exclude:
          # django 5 requires python >=3.10
          - python-version: 3.9
            django-version: 5.0
          - python-version: 3.9
            django-version: 5.1
          # django 6 requires python >=3.12
          - python-version: 3.9
            django-version: 6.0
          - python-version: 3.10
            django-version: 6.0
          - python-version: 3.11
            django-version: 6.0
    name: Test (Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }})

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
        with:
          enable-cache: true
      - run: uv sync --frozen
      - run: uv pip install "Django~=${{ matrix.django-version }}"
      - run: uv run pytest -s --tb=native --random-order -m "not benchmark"

  test-django-prerelease:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    name: Test Django prerelease (Python ${{ matrix.python-version }})

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
        with:
          enable-cache: true
      - run: uv sync --frozen
      - run: uv pip install --pre django
      - run: uv run pytest -s --tb=native --random-order -m "not benchmark"

  typecheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.12
      - name: Set up uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
        with:
          enable-cache: true
      - run: uv sync --frozen
      - run: uv run pyright .
